# Generated by Django 4.1.7 on 2023-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Завдання')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис завдання')),
                ('task_date', models.DateTimeField(auto_now=True, verbose_name='Дата створення')),
                ('is_done', models.BooleanField(default=False, verbose_name='Виконано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.category', verbose_name='Категорія')),
            ],
        ),
    ]
